name = "Fawcett"
uuid = "e51eea1f-b1c1-44ac-894a-6610bfa0995e"
license = "MIT"
authors = ["Alexander L. Hayes <alexander@batflyer.net>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
